/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import projektgrmelaroman.Otazka1zN;

/**
 *
 * @author Roman Grmela <romasg1@seznam.cz>
 */
public class JPanel1of4 extends javax.swing.JPanel {
    
    private Otazka1zN otazka;

    /**
     * Creates new form JPanel1of4
     * @param otazka je aktualni otazka
     */
    public JPanel1of4(Otazka1zN otazka) {
        this.otazka=otazka;
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1z4 = new javax.swing.ButtonGroup();
        JLabel_zobraz_otazku = new javax.swing.JLabel();
        jRadioButton_odpoved1 = new javax.swing.JRadioButton();
        jRadioButton_odpoved2 = new javax.swing.JRadioButton();
        jRadioButton_odpoved3 = new javax.swing.JRadioButton();
        jRadioButton_odpoved4 = new javax.swing.JRadioButton();

        JLabel_zobraz_otazku.setText(this.otazka.getTextOtazky());

        buttonGroup1z4.add(jRadioButton_odpoved1);
        jRadioButton_odpoved1.setText("jRadioButton1");

        buttonGroup1z4.add(jRadioButton_odpoved2);
        jRadioButton_odpoved2.setText("jRadioButton2");

        buttonGroup1z4.add(jRadioButton_odpoved3);
        jRadioButton_odpoved3.setText("jRadioButton3");

        buttonGroup1z4.add(jRadioButton_odpoved4);
        jRadioButton_odpoved4.setText("jRadioButton4");
        jRadioButton_odpoved4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_odpoved4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLabel_zobraz_otazku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton_odpoved1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                    .addComponent(jRadioButton_odpoved2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton_odpoved3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton_odpoved4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(JLabel_zobraz_otazku, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jRadioButton_odpoved1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton_odpoved2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jRadioButton_odpoved3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton_odpoved4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton_odpoved4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_odpoved4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_odpoved4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel_zobraz_otazku;
    private javax.swing.ButtonGroup buttonGroup1z4;
    private javax.swing.JRadioButton jRadioButton_odpoved1;
    private javax.swing.JRadioButton jRadioButton_odpoved2;
    private javax.swing.JRadioButton jRadioButton_odpoved3;
    private javax.swing.JRadioButton jRadioButton_odpoved4;
    // End of variables declaration//GEN-END:variables
}
