/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import projektgrmelaroman.BadQuestionException;
import projektgrmelaroman.Kviz;
import projektgrmelaroman.Otazka;
import projektgrmelaroman.Otazka1zN;



/**
 * 
 * @author Roman Grmela <romasg1@seznam.cz>
 */
public class mainFrame extends javax.swing.JFrame {
    
    ArrayList<Otazka> seznam = new ArrayList<>();//seznam otazek
    private int indexAktualniOtazky=0;
    public Otazka aktualniOtazka;
    
    private int body;//soucet bodu
    
    
  

    /**
     * Creates new form ProjektQFrame
     * @throws BadQuestionException kdyz je chybny format otazky
     */
    public mainFrame() throws BadQuestionException {
        initComponents();
        
        pack();
        setLocationRelativeTo(null); //VYCENTRUJE OKNO
        
        // Vytvoření a zobrazení dialogového okna pro výběr souboru
        JFileChooser soubory = new JFileChooser(".");//vyber aktualni pracovni slozky - > relativni cesta
        int vysledek = soubory.showOpenDialog(this);//Metoda showOpenDialog vrací int hodnotu, která reprezentuje, zda uživatel schválil nebo zrušil dialog.
        
         // Pokud uživatel zruší výběr, ukončete aplikaci
        if (vysledek != JFileChooser.APPROVE_OPTION) {
        System.exit(0);//Pokud result není JFileChooser.APPROVE_OPTION, uživatel zrušil dialog, takže aplikace ukončíme s System.exit(1).
        }
        var soubor = soubory.getSelectedFile();
        
        if(soubor == null){
          System.exit(1);
        }
        
        Kviz k = new Kviz();
        try {
            k.nactiSoubor(soubor.getAbsolutePath());
            String nazevKvizu = k.getNazevKvizu();
            jTextArea_zahlavi.setText(nazevKvizu);
            
            seznam=k.getSeznam();
          
            
        } catch (BadQuestionException ex) {
            JOptionPane.showMessageDialog(null, "Otázce v souboru chybí text.", "Varování", JOptionPane.WARNING_MESSAGE);
            System.exit(0);//0 znamena ok..1 znamena fail
        }
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        group_v_mainpanelu = new javax.swing.ButtonGroup();
        zapati_Jpanel = new javax.swing.JPanel();
        jButtonNext = new javax.swing.JButton();
        exit_Jbutton = new javax.swing.JButton();
        jButtonPrev = new javax.swing.JButton();
        main_panel = new javax.swing.JPanel();
        zahlavi_panel = new javax.swing.JPanel();
        jScrollPane_obali_textArea = new javax.swing.JScrollPane();
        jTextArea_zahlavi = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kvizova aplikace");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(2500, 2500));
        setMinimumSize(new java.awt.Dimension(510, 350));

        jButtonNext.setText("<html><b><u>D</u>alší</b> &rarr;");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        exit_Jbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exit_Jbutton.setText("Konec");
        exit_Jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_JbuttonActionPerformed(evt);
            }
        });

        jButtonPrev.setText("<html>&larr <b><u>P</u>ředchozí</b>");
        jButtonPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout zapati_JpanelLayout = new javax.swing.GroupLayout(zapati_Jpanel);
        zapati_Jpanel.setLayout(zapati_JpanelLayout);
        zapati_JpanelLayout.setHorizontalGroup(
            zapati_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, zapati_JpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(exit_Jbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        zapati_JpanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {exit_Jbutton, jButtonNext, jButtonPrev});

        zapati_JpanelLayout.setVerticalGroup(
            zapati_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zapati_JpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(zapati_JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNext)
                    .addComponent(exit_Jbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jButtonPrev))
                .addContainerGap())
        );

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        zahlavi_panel.setBorder(new javax.swing.border.MatteBorder(null));

        jTextArea_zahlavi.setEditable(false);
        jTextArea_zahlavi.setBackground(new java.awt.Color(204, 255, 204));
        jTextArea_zahlavi.setColumns(20);
        jTextArea_zahlavi.setFont(new java.awt.Font("David Libre", 0, 24)); // NOI18N
        jTextArea_zahlavi.setRows(5);
        jScrollPane_obali_textArea.setViewportView(jTextArea_zahlavi);

        javax.swing.GroupLayout zahlavi_panelLayout = new javax.swing.GroupLayout(zahlavi_panel);
        zahlavi_panel.setLayout(zahlavi_panelLayout);
        zahlavi_panelLayout.setHorizontalGroup(
            zahlavi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, zahlavi_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_obali_textArea)
                .addContainerGap())
        );
        zahlavi_panelLayout.setVerticalGroup(
            zahlavi_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zahlavi_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_obali_textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zapati_Jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(main_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(zahlavi_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(zahlavi_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zapati_Jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrevActionPerformed

    private void exit_JbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_JbuttonActionPerformed
         System.exit(0);//zavre aplikaci
    }//GEN-LAST:event_exit_JbuttonActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
        indexAktualniOtazky = indexAktualniOtazky + 1;
        
    }//GEN-LAST:event_jButtonNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {//NASTAVENÍ VZHLEDU APLIKACE
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new mainFrame().setVisible(true);
                } catch (BadQuestionException ex) {
                    Logger.getLogger(mainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton exit_Jbutton;
    private javax.swing.ButtonGroup group_v_mainpanelu;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrev;
    private javax.swing.JScrollPane jScrollPane_obali_textArea;
    private javax.swing.JTextArea jTextArea_zahlavi;
    private javax.swing.JPanel main_panel;
    private javax.swing.JPanel zahlavi_panel;
    private javax.swing.JPanel zapati_Jpanel;
    // End of variables declaration//GEN-END:variables
}
