/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package generator;

import javax.swing.JOptionPane;

/**
 *
 * @author David Martinek <martinek zavináč gvid.cz>
 */
public class Okno extends javax.swing.JFrame
{

  private final static int MOD_ZDVORILY = 0;
  private final static int MOD_HOVOROVY = 1;
  private final static int MOD_NEZDVORILY = 2;
  
  private int vybranyMod = MOD_ZDVORILY;
  
  /**
   * Creates new form Okno1
   */
  public Okno()
  {
    initComponents();
    this.setLocationRelativeTo(null); // vycentruje okno na obrazovce
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    buttonGroup1 = new javax.swing.ButtonGroup();
    jPanel1 = new javax.swing.JPanel();
    zdvorilyRadioButton = new javax.swing.JRadioButton();
    hovorovyRadioButton = new javax.swing.JRadioButton();
    nezdvorilyRadioButton = new javax.swing.JRadioButton();
    jLabel3 = new javax.swing.JLabel();
    osloveniTextField = new javax.swing.JTextField();
    jPanel2 = new javax.swing.JPanel();
    stiskniMeButton = new javax.swing.JButton();
    zpravaTextField = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Generátor pozdravů");
    setBounds(new java.awt.Rectangle(0, 0, 0, 0));
    setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
    setLocation(new java.awt.Point(200, 200));
    setMinimumSize(new java.awt.Dimension(320, 240));

    jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Výběr zdvořilostního módu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, getFont()));
    jPanel1.setFont(getFont());

    buttonGroup1.add(zdvorilyRadioButton);
    zdvorilyRadioButton.setFont(getFont());
    zdvorilyRadioButton.setSelected(true);
    zdvorilyRadioButton.setText("Zdvořilý");
    zdvorilyRadioButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        zdvorilyRadioButtonActionPerformed(evt);
      }
    });
    jPanel1.add(zdvorilyRadioButton);

    buttonGroup1.add(hovorovyRadioButton);
    hovorovyRadioButton.setFont(getFont());
    hovorovyRadioButton.setText("Hovorový");
    hovorovyRadioButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        hovorovyRadioButtonActionPerformed(evt);
      }
    });
    jPanel1.add(hovorovyRadioButton);

    buttonGroup1.add(nezdvorilyRadioButton);
    nezdvorilyRadioButton.setFont(getFont());
    nezdvorilyRadioButton.setText("Nezdvořilý");
    nezdvorilyRadioButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        nezdvorilyRadioButtonActionPerformed(evt);
      }
    });
    jPanel1.add(nezdvorilyRadioButton);

    jLabel3.setFont(getFont());
    jLabel3.setText("Jak tě mám oslovit?");

    osloveniTextField.setFont(getFont());
    osloveniTextField.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        osloveniTextFieldActionPerformed(evt);
      }
    });

    stiskniMeButton.setFont(getFont());
    stiskniMeButton.setText("Generuj pozdrav");
    stiskniMeButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        stiskniMeButtonActionPerformed(evt);
      }
    });
    jPanel2.add(stiskniMeButton);

    zpravaTextField.setEditable(false);
    zpravaTextField.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
    zpravaTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
    zpravaTextField.setBorder(null);
    zpravaTextField.setDragEnabled(true);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(zpravaTextField)
          .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(osloveniTextField)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(osloveniTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(zpravaTextField)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private final static boolean DIALOG_ANO = true;
  private final static boolean DIALOG_NE = false;
  
  private void nastavZpravu(boolean zobrazitDialog)
  {
    String osloveni = osloveniTextField.getText();
    if (osloveni.length() == 0)
    {
      if (zobrazitDialog)
        JOptionPane.showMessageDialog(rootPane, "Nejprve zadej, jak tě mám oslovovat!", "Varování", JOptionPane.WARNING_MESSAGE);      
      return;
    }
    
    switch (vybranyMod)
    {
      case MOD_ZDVORILY:
        zpravaTextField.setText("Poníženě si dovoluji přáti dobrý den, " + osloveni + ".");
        break;
      
      case MOD_HOVOROVY:
        zpravaTextField.setText("Čaues " + osloveni + "! Jak je?");
        break;
        
      case MOD_NEZDVORILY:
        zpravaTextField.setText("Tě péro, sombréro! Jak de život, " + osloveni + "?");
        break;
    }

  }
  
  private void stiskniMeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_stiskniMeButtonActionPerformed
  {//GEN-HEADEREND:event_stiskniMeButtonActionPerformed
    nastavZpravu(DIALOG_ANO);
  }//GEN-LAST:event_stiskniMeButtonActionPerformed

  private void zdvorilyRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_zdvorilyRadioButtonActionPerformed
  {//GEN-HEADEREND:event_zdvorilyRadioButtonActionPerformed
    this.vybranyMod = MOD_ZDVORILY;
    nastavZpravu(DIALOG_NE);
  }//GEN-LAST:event_zdvorilyRadioButtonActionPerformed

  private void hovorovyRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_hovorovyRadioButtonActionPerformed
  {//GEN-HEADEREND:event_hovorovyRadioButtonActionPerformed
    this.vybranyMod = MOD_HOVOROVY;
    nastavZpravu(DIALOG_NE);
  }//GEN-LAST:event_hovorovyRadioButtonActionPerformed

  private void nezdvorilyRadioButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nezdvorilyRadioButtonActionPerformed
  {//GEN-HEADEREND:event_nezdvorilyRadioButtonActionPerformed
    this.vybranyMod = MOD_NEZDVORILY;
    nastavZpravu(DIALOG_NE);
  }//GEN-LAST:event_nezdvorilyRadioButtonActionPerformed

  private void osloveniTextFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_osloveniTextFieldActionPerformed
  {//GEN-HEADEREND:event_osloveniTextFieldActionPerformed
    nastavZpravu(DIALOG_ANO);
  }//GEN-LAST:event_osloveniTextFieldActionPerformed

   /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /*
     * Set the Nimbus look and feel
     */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the
     * default look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("GTK+".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
//      String info = javax.swing.UIManager.getSystemLookAndFeelClassName();
//      javax.swing.UIManager.setLookAndFeel(info);
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(Okno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /*
     * Create and display the form
     */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new Okno().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.ButtonGroup buttonGroup1;
  private javax.swing.JRadioButton hovorovyRadioButton;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JRadioButton nezdvorilyRadioButton;
  private javax.swing.JTextField osloveniTextField;
  private javax.swing.JButton stiskniMeButton;
  private javax.swing.JRadioButton zdvorilyRadioButton;
  private javax.swing.JTextField zpravaTextField;
  // End of variables declaration//GEN-END:variables
}
