/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scitacka;

import javax.swing.JOptionPane;

/**
 *
 * @author David Martinek <martinek zavináč gvid.cz>
 */
public class Scitacka extends javax.swing.JFrame
{

  /**
   * Creates new form Scitacka
   */
  public Scitacka()
  {
    initComponents();
    this.setLocationRelativeTo(null); // vycentruje okno na obrazovce
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    prvniTextField = new javax.swing.JTextField();
    druhyTextField = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    vysledekTextField = new javax.swing.JTextField();
    jPanel1 = new javax.swing.JPanel();
    rovnaseButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Sčítačka");
    setMinimumSize(new java.awt.Dimension(250, 250));

    prvniTextField.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
    prvniTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

    druhyTextField.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
    druhyTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

    jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("+");

    vysledekTextField.setEditable(false);
    vysledekTextField.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
    vysledekTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

    jPanel1.setLayout(new java.awt.GridLayout());

    rovnaseButton.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
    rovnaseButton.setText("   =   ");
    rovnaseButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        rovnaseButtonActionPerformed(evt);
      }
    });
    jPanel1.add(rovnaseButton);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(prvniTextField)
          .addComponent(druhyTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
          .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(vysledekTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(prvniTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(druhyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(5, 5, 5)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(vysledekTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void rovnaseButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rovnaseButtonActionPerformed
  {//GEN-HEADEREND:event_rovnaseButtonActionPerformed
    try 
    {
      double x = Double.parseDouble(prvniTextField.getText());
      double y = Double.parseDouble(druhyTextField.getText());
      double vysledek = x + y;
      vysledekTextField.setText("" + vysledek);
    }
    catch (NumberFormatException e)
    {
      JOptionPane.showMessageDialog(rootPane, "Zadal jsi něco, co není číslo!", "Chyba výpočtu", JOptionPane.WARNING_MESSAGE);
    }
    
  }//GEN-LAST:event_rovnaseButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /*
     * Set the Nimbus look and feel
     */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the
     * default look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("GTK+".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(Scitacka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(Scitacka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(Scitacka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(Scitacka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /*
     * Create and display the form
     */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new Scitacka().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField druhyTextField;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JTextField prvniTextField;
  private javax.swing.JButton rovnaseButton;
  private javax.swing.JTextField vysledekTextField;
  // End of variables declaration//GEN-END:variables
}
